#!/usr/bin/env bash
# Function to display subdomain information using dig
display_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local record_type="A"

    if [[ -n $subdomain ]]; then
        subdomain="$subdomain.$domain"
    else
        subdomain="www lb-01 web-01 web-02"
    fi

    for sub in $subdomain; do
        destination=$(dig +short $sub.$domain)
        if [[ -z $destination ]]; then
            echo "The subdomain $sub does not have a valid IP address"
        else
            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

# Main script logic
if [[ $# -lt 1 ]]; then
    echo "Error: Missing domain parameter"
    exit 1
fi

domain=$1
subdomain=$2

display_subdomain_info $domain $subdomain
