#!/usr/bin/env bash

# Check four required parameters are provided
if [ $# -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_to_transfer="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_to_transfer" "$username@$server_ip":~/

if [ $? -eq 0 ]; then
  echo "File successfully transferred to $username@$server_ip:~/"
else
  echo "Error transferring the file."
fi
