#!/usr/bin/env bash
# Configure Nginx

balancer="\
frontend haproxy_balancer
    bind *:8080
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 352375-web-01 52.206.20.95:80 check
    server 352375-web-02 54.86.169.176:80 check"

apt-get -y update
apt-get -y upgrade

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
