#!/usr/bin/env bash
# displays a list of currently running processes.
# Use 'ps' command to display all processes, for all users, including those without a TTY.
# Format the output with user-oriented information and process hierarchy.
ps -eo pid,ppid,user,%cpu,%mem,cmd --forest
