#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and prints Hi at 9
i=0
while ((i < 10))
do
        echo "Best School"
        ((i++))
        if [ $i -eq 9 ]
        then
                echo "Hi"
        fi
done
